name: rightnow
description: Rightnow Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.51+34

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  freezed: ^2.4.7
  flutter_bloc: ^8.1.3
  json_annotation: ^4.0.1
  file_picker: ^8.1.4
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  #flutter_search_bar: ^3.0.0-dev.1
  uuid: ^4.5.1
  collection: ^1.15.0
  image_picker: ^1.0.7
  shared_preferences: ^2.0.5
  flutter_screenutil: ^5.0.0+2
  google_maps_flutter: ^2.0.3
  location: ^6.0.2 #7.0.1
  material_design_icons_flutter: ^7.0.7296
  screenshot: ^3.0.0
  flutter_simple_dependency_injection: ^2.0.0
  easy_localization: ^3.0.0
  jiffy: ^6.2.1
  change_app_package_name: ^1.0.0
  video_player: ^2.9.2
  url_launcher: ^6.0.9
  youtube_player_flutter: ^9.1.1
  #simple_url_preview: ^3.0.1
  flutter_native_splash: ^2.3.10
  rflutter_alert: ^2.0.4
  image_cropper: ^8.0.2
  flutter_sound: ^9.25.1 #^9.2.13
  flutter_phoenix: ^1.0.0
  scrollable_positioned_list: ^0.3.8
  provider: ^6.0.0
  hive: ^2.0.4
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  firebase_messaging: ^15.1.5
  badges: ^3.1.2
  signature: ^5.4.1
  path_provider: ^2.0.4
  permission_handler: ^11.2.1
  flutter_html: ^3.0.0-beta.2
  #flutter_barcode_scanner: ^2.0.0
  #file_saver: ^0.2.9
  #microphone: ^0.1.0
  google_maps_flutter_web: ^0.5.4+3
  #open_file: ^3.3.2
  mobile_scanner: ^6.0.2
  flutter_sound_web: ^9.25.1
  #open_file:
  #  path: ../packages/open_file
  #open_file_safe: ^3.2.3

#dependency_overrides:
#  analyzer: '0.40.4'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.0

#dependency_overrides:
#  flutter_inappwebview:
#    git:
#      url: https://github.com/rshrc/flutter_inappwebview
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  #translation_generator:
    #path: ../packages/translation_generator
  #floor_generator: ^1.1.0
  build_runner: ^2.0.2
  json_serializable: ^6.7.1
  #to_string_generator: ^1.2.1
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/rightnow.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
    
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/translations/en.json
    - assets/translations/fr.json
    - assets/translations/ar-DZ.json
    
  fonts:
    - family: PoppinsMedium
      fonts: 
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
