// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1lc_ObwNCSX3TLEG4--Uy-io9wj6VmNA',
    appId: '1:200927658646:web:e78a73ab3707fe2677b8b7',
    messagingSenderId: '200927658646',
    projectId: 'rightnow-318113',
    authDomain: 'rightnow-318113.firebaseapp.com',
    storageBucket: 'rightnow-318113.appspot.com',
    measurementId: 'G-EVFEGD5Y68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBCK-D7vKx9VrmUNISYMYNmQCOeRWGQk',
    appId: '1:200927658646:android:e93468b4c8fbfef977b8b7',
    messagingSenderId: '200927658646',
    projectId: 'rightnow-318113',
    storageBucket: 'rightnow-318113.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2ArI_4Qx-JN01pABpz0zeZlzCnbWqhg',
    appId: '1:200927658646:ios:541d1ef903ff07b477b8b7',
    messagingSenderId: '200927658646',
    projectId: 'rightnow-318113',
    storageBucket: 'rightnow-318113.appspot.com',
    androidClientId: '200927658646-eujgf82m515b5icbr5inr9ogfin3mc5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.apoce',
  );
}
